-- 4-1
SELECT * FROM EXAM4_1;

SELECT ID FROM EXAM4_1
GROUP BY ID
HAVING COUNT(*) = 2
ORDER BY (CASE WHEN ID =999 THEN 0 ELSE ID END);

DROP TABLE EXAM4_1;

SELECT ID FROM EXAM4_1
GROUP BY ID
-- HAVING COUNT(*) = 2
ORDER BY (CASE WHEN ID =999 THEN 0 ELSE ID END);

-- 4-2
SELECT * FROM EXAM4_2;

-- 1
SELECT 지역, SUM(매출금액) AS 매출금액
FROM EXAM4_2
GROUP BY 지역
ORDER BY 매출금액 DESC;

-- 2
SELECT 지역, 매출금액
FROM EXAM4_2
ORDER BY 년 DESC;

-- 3
SELECT 지역, 매출금액
FROM EXAM4_2
GROUP BY 지역
ORDER BY 년 DESC;

SELECT 지역, SUM(매출금액) AS 매출금액
FROM EXAM4_2
GROUP BY 지역
ORDER BY 매출금액 DESC;

-- 4
SELECT 지역, SUM(매출금액) AS 매출금액
FROM EXAM4_2
GROUP BY 지역
HAVING SUM(매출금액) >10000
ORDER BY COUNT(*) ASC;

-- 4-3
CREATE TABLE EXAM4_3_1 (A NUMBER(10));
INSERT INTO EXAM4_3_1 VALUES(1);
INSERT INTO EXAM4_3_1 VALUES(NULL);
INSERT INTO EXAM4_3_1 VALUES(3);
INSERT INTO EXAM4_3_1 VALUES(7);
INSERT INTO EXAM4_3_1 VALUES(2);
INSERT INTO EXAM4_3_1 VALUES(NULL);

SELECT * FROM EXAM4_3_1;

SELECT * FROM EXAM4_3_1
ORDER BY A;

SELECT * FROM EXAM4_3_1
ORDER BY A DESC;

SELECT A, A+1, A*2, A-3, A/4 FROM EXAM4_3_1; -- NULL은 항상 NULL

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 매출합계 DESC;

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 매출금액 DESC;  -- X

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY SUM(매출금액) DESC;

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 1 DESC;  -- 지역의 내림차순 1 = 지역 2 = SUM


SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 지역, 매출합계;

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 1, 매출합계;

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 1, 2;

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 지역, 2;

SELECT 지역, SUM(매출금액) AS 매출합계
FROM EXAM4_2
GROUP BY 지역
ORDER BY 3; -- 1,2 만 존재


-- 4-5
SELECT * FROM EXAM4_4;

SELECT ID, AMT
FROM EXAM4_4
ORDER BY(
CASE 
    WHEN ID='A' THEN 1
    ELSE 2
    END),
AMT DESC;

SELECT ID, AMT
FROM EXAM4_4
ORDER BY(
CASE 
    WHEN ID='A' THEN 1
    ELSE 2
    END),
AMT;
