-- 4-1
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT * FROM EMP, DEPT;

SELECT * FROM EMP CROSS JOIN DEPT;

SELECT * FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP A, DEPT B
WHERE A.DEPTNO = B.DEPTNO;

SELECT * FROM EMP JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP A JOIN DEPT B
ON A.DEPTNO = B.DEPTNO;

SELECT * FROM EMP A JOIN DEPT B
USING (DEPTNO);

SELECT * FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP
CROSS JOIN DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP
NATURAL JOIN DEPT;


-- 5
SELECT * FROM EXAM5_1;
SELECT * FROM EXAM5_2;
SELECT * FROM EXAM5_1 X LEFT OUTER JOIN EXAM5_2 Y
ON X.C=Y.C;

SELECT * FROM EXAM5_1 X FULL OUTER JOIN EXAM5_2 Y
ON X.C=Y.C;

-- 7 
SELECT * FROM EXAM7_1 A LEFT OUTER JOIN EXAM7_2 B
ON (A.C1 = B.C1 AND B.C2 BETWEEN 1 AND 3);
SELECT * FROM EXAM7_1;

-- 10
SELECT A, B, C FROM EXAM10_1
UNION ALL
SELECT A, B, C FROM EXAM10_2;

SELECT A, B, C FROM EXAM10_1
UNION 
SELECT A, B, C FROM EXAM10_2;

-- 11 
SELECT COL1, COL2, COUNT(*) AS CNT 
FROM (SELECT COL1, COL2 
FROM EXAM11_1
UNION ALL
SELECT COL1, COL2
FROM EXAM11_2
UNION
SELECT COL1, COL2
FROM EXAM11_1)
GROUP BY COL1, COL2;

-- 13
SELECT * FROM EXAM13;

SELECT C3
FROM EXAM13
START WITH C2 IS NULL
CONNECT BY PRIOR C1=C2
ORDER SIBLINGS BY C3 DESC;

SELECT C3
FROM EXAM13
START WITH C2 IS NULL
CONNECT BY PRIOR C1=C2;

SELECT C3
FROM EXAM13
START WITH C2 IS NULL
CONNECT BY PRIOR C1=C2
ORDER BY C3 DESC;

-- 15
SELECT 사원번호, 사원명, 입사일자, 매니저사원번호
FROM EXAM15
START WITH 매니저사원번호 IS NULL
CONNECT BY PRIOR 사원번호 = 매니저사원번호
AND 입사일자 BETWEEN '2013-01-01' AND '2013-12-31'
ORDER SIBLINGS BY 사원번호;

SELECT 사원번호, 사원명, 입사일자, 매니저사원번호
FROM EXAM15
START WITH 매니저사원번호 IS NULL
CONNECT BY PRIOR 사원번호 = 매니저사원번호
AND 입사일자 BETWEEN '2013-01-01' AND '2013-12-31';

SELECT 사원번호, 사원명, 입사일자, 매니저사원번호
FROM EXAM15
START WITH 매니저사원번호 IS NULL
CONNECT BY PRIOR 사원번호 = 매니저사원번호
AND 입사일자 BETWEEN '2013-01-01' AND '2013-12-31'
ORDER SIBLINGS BY 사원번호 DESC;

-- 17
SELECT COUNT(DISTINCT A||B)
FROM EXAM17_1
WHERE D=(SELECT D FROM EXAM17_2 WHERE E='i');

SELECT *
FROM EXAM17_1
WHERE D=(SELECT D FROM EXAM17_2 WHERE E='i');