-- 14
SELECT * FROM EXAM14_1;
SELECT * FROM EXAM14_2;
SELECT * FROM EXAM14_3;

SELECT * FROM EXAM14_1
UNION ALL
SELECT * FROM EXAM14_2
MINUS
SELECT * FROM EXAM14_3;

SELECT * FROM EXAM14_1
UNION ALL
SELECT * FROM EXAM14_2;

-- 21
SELECT * FROM EXAM21_1;

SELECT ID, PARENT_ID, NAME, PARENT_NAME
FROM EXAM21_1
WHERE PARENT_ID NOT IN(3)
START WITH PARENT_ID = 0
CONNECT BY PRIOR ID = PARENT_ID
ORDER SIBLINGS BY parent_id ASC,
ID ASC;

SELECT ID, PARENT_ID, NAME, PARENT_NAME
FROM EXAM21_1
WHERE PARENT_ID NOT IN(3)
START WITH PARENT_ID = 0
CONNECT BY PRIOR ID = PARENT_ID
ORDER BY parent_id ASC,
ID ASC;

