-- 5-1
CREATE TABLE EMP_10(A NUMBER(10));
CREATE TABLE 100-EMP(A NUMBER(10));
CREATE TABLE EMP-100(A NUMBER(10));
CREATE TABLE 100_EMP(A NUMBER(10));

-- 5-2, 4, 9~11
CREATE TABLE 학생 (학번 CHAR(8) PRIMARY 
KEY, 장학금 INTEGER);
SELECT * FROM 학생;

INSERT INTO 학생 VALUES(1,10);
INSERT INTO 학생 VALUES(2,20);
INSERT INTO 학생 VALUES(3,30);
INSERT INTO 학생 VALUES(4,40);
INSERT INTO 학생 VALUES(5,50);
INSERT INTO 학생 VALUES(6,NULL);
INSERT INTO 학생 VALUES(NULL,70); -- PK

SELECT COUNT(*) FROM 학생; -- 6
SELECT COUNT(학번) FROM 학생; -- 6
SELECT COUNT(장학금) FROM 학생; -- 5

DELETE FROM 학생; -- 전부 삭제
DELETE FROM 학생 WHERE 장학금 = 10;
DELETE FROM 학생 WHERE 장학금 = NULL; -- 비교연산시 알 수 없음. 찾을게 없다.
DELETE FROM 학생 WHERE 장학금 IS NULL; 
DELETE FROM 학생 WHERE 장학금 IS NOT NULL; -- 장학금 IS NOT NULL

TRUNCATE TABLE 학생;
DROP TABLE 학생;

ALTER TABLE 학생 DROP COLUMN 장학금;
ALTER TABLE 학생 DROP COLUMN 학생;

-- 5-5
CREATE TABLE 부서 ( 부서번호 CHAR(10), 부서명 
CHAR(10), PRIMARY KEY(부서번호));

CREATE TABLE 직원 ( 직원번호 CHAR(10), 소속부서 
CHAR(10), PRIMARY KEY(직원번호),
FOREIGN KEY(소속부서) REFERENCES 부서(부서번호) 
ON DELETE CASCADE);

SELECT * FROM 부서;
SELECT * FROM 직원;

INSERT INTO 부서 VALUES('10', '영업과');
INSERT INTO 부서 VALUES('20', '기획과');

INSERT INTO 직원 VALUES('1000', '10');
INSERT INTO 직원 VALUES('2000', '20');
INSERT INTO 직원 VALUES('3000', '20');
COMMIT;

SELECT COUNT(직원번호) FROM 직원; -- A -> 3
DELETE FROM 부서 WHERE 부서번호 = '20'; -- B
SELECT COUNT(직원번호) FROM 직원; -- C -> 1

-- 5-7
CREATE TABLE TBL
( ID NUMBER PRIMARY KEY, AMT NUMBER NOT NULL, DEGREE VARCHAR2(1)
);

INSERT INTO TBL VALUES(1,100); -- 1
INSERT INTO TBL(ID, AMT, DEGREE) VALUES(2, 200, 'AB'); --2
INSERT INTO TBL(ID, DEGREE) VALUES(4, 'X'); --3
INSERT INTO TBL(ID, AMT) VALUES(3, 300); -- 4
INSERT INTO TBL VALUES(5, 500, NULL); --5

SELECT * FROM TBL;

-- 5-8
CREATE TABLE BOARD
(
BOARD_ID VARCHAR2(10) NOT NULL,
BOARD_NM VARCHAR2(50) NOT NULL,
USE_YM VARCHAR2(1) NOT NULL,
REG_DATE DATE NOT NULL,
BOARD_DESC VARCHAR2(100) NULL
);

SELECT * FROM BOARD;

INSERT INTO BOARD VALUES(1, 'QA', 'Y', SYSDATE, 'QA 게시판'); -- 1

INSERT INTO BOARD (BOARD_ID, BOARD_NM, 
USE_YM, BOARD_DESC) VALUES ('100', 'FAQ', 'Y', 
'FAQ 게시판'); -- 2

UPDATE BOARD SET USE_YM = 'N' WHERE 
BOARD_ID='1'; -- 3

INSERT INTO BOARD VALUES(100, 'QA', 'Y', SYSDATE, 'QA 게시판');
UPDATE BOARD SET BOARD_ID=200 WHERE 
BOARD_ID='100'; -- 4


