-- 21
SELECT * FROM EXAM21;

SELECT COUNT(NVL(USERCOUNT,0)) FROM EXAM21;
SELECT SUM(NVL(USERCOUNT,0))/4 FROM EXAM21;
SELECT AVG(NVL(USERCOUNT,0)) FROM EXAM21;
SELECT AVG(NVL(USERCOUNT,1))-0.5 FROM EXAM21;

-- 23
SELECT * FROM EXAM23;
SELECT SUM(COL1+COL2+COL3+COL4)
FROM EXAM23;
SELECT SUM(COL1) + SUM(COL2) + SUM(COL3) + SUM(COL4)
FROM EXAM23;

-- 25
SELECT * FROM EXAM25;
SELECT SUM(price) AS TOTAL
FROM EXAM25 WHERE orderyear BETWEEN
'2020' AND '2021' AND ordermonth
BETWEEN '01' AND '12';

SELECT SUM(price) AS TOTAL
FROM EXAM25 WHERE ordermonth in('01','06');

SELECT SUM(price) AS TOTAL
FROM EXAM25 WHERE ordermonth in('01', '06');

SELECT SUM(decode('06', 0, price)) AS TOTAL
FROM EXAM25 WHERE orderyear BETWEEN
'2022' AND '2021';

-- 29
SELECT * FROM EXAM29_1;
SELECT * FROM EXAM29_2;
INSERT INTO EXAM29_2 VALUES(NULL);

SELECT COUNT(*)
FROM EXAM29_1 A
WHERE A.COL NOT IN (SELECT COL
FROM EXAM29_2);


-- 30
SELECT * FROM EXAM30;
SELECT * FROM EXAM30 WHERE COL1 IN(1,2,NULL);

-- 31
SELECT * FROM EXAM31;

SELECT * FROM EXAM31 WHERE USERNAME LIKE '%H';
SELECT * FROM EXAM31 WHERE USERNAME LIKE '%#_%';
SELECT * FROM EXAM31 WHERE USERNAME LIKE '%@_%' ESCAPE '@';
SELECT * FROM EXAM31 WHERE USERNAME LIKE '%_%' ESCAPE '_';

-- 34
SELECT * FROM EXAM34;
SELECT * FROM EXAM34_1;

SELECT A.JUMUN AS "주문", B.CUSTRANK AS "고객등급"
FROM (SELECT JUMUN, SUM(PRICE) AS TOTAL
FROM EXAM34
GROUP BY JUMUN)A, EXAM34_1 B
WHERE A.TOTAL BETWEEN B.MINPRICE AND
B.MAXPRICE;

-- 40
SELECT * FROM EMP;
SELECT JOB, COUNT(*) AS ROWCNT
FROM EMP
GROUP BY JOB;

SELECT JOB, COUNT(*) AS ROWCNT
FROM EMP
GROUP BY JOB
ORDER BY JOB;

SELECT JOB, COUNT(*) AS ROWCNT
FROM EMP
GROUP BY JOB
ORDER BY ROWCNT DESC;

SELECT JOB, COUNT(*) AS ROWCNT
FROM EMP
GROUP BY JOB
ORDER BY COUNT(*);

SELECT JOB, COUNT(*) AS ROWCNT
FROM EMP
GROUP BY JOB
ORDER BY 3;

SELECT JOB, COUNT(*) AS ROWCNT
FROM EMP
GROUP BY JOB
ORDER BY 2;

-- 42
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT * FROM EMP CROSS JOIN DEPT;
SELECT * FROM EMP NATURAL JOIN DEPT;

SELECT * FROM EMP CROSS JOIN DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP NATURAL JOIN DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP JOIN DEPT
USING(DEPTNO);

-- 44
SELECT * FROM EXAM44;
SELECT * FROM EXAM44_1;

SELECT b.grade, a.StudentNo, SUM(b.grade)
FROM EXAM44 a, EXAM44_1 b
GROUP BY
GROUPING SETS (b.grade, (b.grade, a.StudentNo));

SELECT b.grade, a.StudentNo, SUM(b.grade)
FROM EXAM44 a, EXAM44_1 b
GROUP BY ROLLUP(B.GRADE, A.STUDENTNO);

SELECT b.grade, a.StudentNo, SUM(b.grade)
FROM EXAM44 a, EXAM44_1 b
GROUP BY CUBE(B.GRADE, A.STUDENTNO);

-- 45
SELECT * FROM EXAM46;

SELECT C1, C2
FROM EXAM46
ORDER BY C1, C2 DESC NULLS LAST;

-- 49
CREATE TABLE TEST49 (
    COL1 VARCHAR(10),
    COL2 VARCHAR(10),
    COL3 NUMBER(10)
);
INSERT INTO TEST49 VALUES('A','가',10);
INSERT INTO TEST49 VALUES('A','가',20);
INSERT INTO TEST49 VALUES('A','다',25);
INSERT INTO TEST49 VALUES('B','가',10);
INSERT INTO TEST49 VALUES('B','나',30);
INSERT INTO TEST49 VALUES('B','나',20);
INSERT INTO TEST49 VALUES('B','나',60);
INSERT INTO TEST49 VALUES('C','라',30);

SELECT * FROM TEST49;

SELECT NTILE_2, COUNT(*) AS ROWCNT
FROM (
SELECT COL1, COL2, COL3, NTILE(3) OVER
(ORDER BY COL3) AS NTILE_2
FROM TEST49)
GROUP BY NTILE_2;

-- 50
SELECT * FROM EXAM50;
SELECT ENAME, SAL,
COUNT(*) OVER(ORDER BY SAL RANGE BETWEEN 50 PRECEDING AND 100 FOLLOWING)
AS SIM_CNT
FROM EXAM50;

SELECT ENAME, SAL,
COUNT(*) OVER(ORDER BY SAL RANGE BETWEEN 99 PRECEDING AND 199 FOLLOWING)
AS SIM_CNT
FROM EXAM50;

